### ISSUE TITLE
Quality Control for non-LOFAR images

### ISSUE THREAD

**Issue by AntoniaR** [transientskp/tkp#412] opened 2015-04-01 03:53 UTC
Implement a basic RMS quality control functionality for all images input into TraP. Reject images with RMS above/below input thresholds, similar to that currently used for LOFAR but not using the theoretical noise.

**Comment by gijzelaerr** [comment] 2016-06-23 09:58
I think this is a duplicate of https://github.com/transientskp/tkp/issues/512

**Closed by gijzelaerr** 2016-06-23 09:58 UTC
Labels: enhancement, priority high
