### ISSUE TITLE
Add Python3 support

### ISSUE THREAD

**Issue by gijzelaerr** [transientskp/tkp#371] opened 2015-01-14 12:11 UTC
Numpy, scipy and django have support for Python3 now. I think Pyrap will receive some love soon, hopefully the'll think about Python3 support. That means that most of our dependencies have support for Python3 now. I think it is a good long term investment to investigate how much work it would be to support Python3 and which libraries do (not) support Python3. Many interesting new features are popping up in Python3 and I want to prevent the developers of TRAP having to work with ancient technology in a couple of years. We don't use obscure standard libraries like StringIO so most of the code can be adjusted with a tool like 2to3.py.

If we decide not to add support Python3 for now, we should write down some coding guide lines that would make support for Python3 in the long term less of a pain.

@jdswinbank: I definitely agree that this would be nice, but it does rather depend on the plans of the pyrap developers: until they say something concrete, we shouldn't count on it happening any time soon. No harm asking them, though... Regarding coding guidelines, I encourage you (and everybody else!) to just edit the docs as appropriate and PR your changes. We can then discuss/argue/mull over/etc the suggested standard as a group.

moved from LOFAR issue tracker:
https://support.astron.nl/lofar_issuetracker/issues/5745

**Comment by gijzelaerr** [comment] 2015-05-28 13:30
pyrap has been renamed to python-casacore, and the next release will have python3 support.

**Comment by HannoSpreeuw** [comment] 2020-07-08 13:50
Any news on Python 3 support?

**Comment by HannoSpreeuw** [comment] 2020-07-08 14:03
`pipenv install tkp` works after `sudo pacman -S postgresql-libs` (Manjaro Linux with Python 3).

**Comment by gijzelaerr** [comment] 2020-07-08 14:03
The project didn't see any serious development for 3 years, i don't think python3 support will arrive any time soon.

**Comment by HannoSpreeuw** [comment] 2020-07-08 14:07
Well, here I am as the NLeSC engineer for the [The PetaFLOP AARTFAAC Data-Reduction Engine (PADRE)](https://www.esciencecenter.nl/projects/the-petaflop-aartfaac-data-reduction-engine-padre/).

However, my first assignment is to speed up PySE, not to port it to Python 3.

**Comment by AntoniaR** [comment] 2020-07-08 14:28
Mark is recruited till Christmas to do a number of things including this. We have also just been awarded money through a couple of ASTRON computing grants. So TraP development is starting actively again soon.

**Comment by AntoniaR** [comment] 2020-07-15 08:45
This is a key priority for Release 5.0

**Comment by AntoniaR** [comment] 2021-07-22 10:40
Also upgrade to use the latest version of sqlalchemy - see issue #586

**Comment by HannoSpreeuw** [comment] 2022-08-18 09:07
I am embarking on this now, but also facing a number of errors from

`python runtests.py -v`

Attached is _all_errors_from_runtests.py.txt_  from 
`python runtests.py -v > all_output_from_runtests.py.txt 2>&1`
`cat all_output_from_runtests.py.txt | grep -i error | grep -v error_radius > all_errors_from_runtests.py.txt 2>&1`

This means I excluded all lines with `error_radius`.

Not sure if these errors should be fixed before I proceed with the Python 2 to 3 translation.

[all_errors_from_runtests.py.txt](https://github.com/transientskp/tkp/files/9372104/all_errors_from_runtests.py.txt)

**Comment by HannoSpreeuw** [comment] 2022-08-18 12:35
I think I can ignore all errors related to the output from the PySE sourcefinder for now, since there is a new Python 3 version waiting in the master branch of the [PySE standalone repo](https://github.com/transientskp/pyse).

Once integrated with the rest of TraP, some of these sourcefinder related errors will disappear and others will emerge. Best to tackle them after integration.

**Comment by HannoSpreeuw** [comment] 2022-08-18 13:53
Two of them are of the type **ERROR:tkp.db.database:Query failed: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint**, similar to issue #566, but slightly different from`violates unique constraint "ix_varmetric_runcat"`.

`python runtests -v` yielded `violates unique constraint "runningcatalog_xtrsrc_key"` and `violates unique constraint "config_dataset_section_key_key"`.

Perhaps these two errors are also caused by too complex queries, as suggested [in the discussion of that issue](https://github.com/transientskp/tkp/issues/566#issuecomment-535550988), I cannot tell.

**Comment by HannoSpreeuw** [comment] 2022-08-25 15:15
To fix the other errors and broken unit tests, I will run `python runtests.py -v` through a debugger, because I cannot understand what the cause of the problem is from the output only.

**Comment by AntoniaR** [comment] 2022-08-30 08:15
Hi! Sorry for not getting back to you on this issue sooner. What exact errors are you getting? 

If I remember correctly, the last time I tested the master branch there were no significant errors. Are you running TraP in a virtual environment and installing it as explained here: https://tkp.readthedocs.io/en/latest/getstart/installation.html#install-tkp
i.e.
```
$ git clone https://github.com/transientskp/tkp.git
$ cd tkp
$ pip install -e ".[pixelstore]"
```

That should then install all the dependencies too.

**Comment by HannoSpreeuw** [comment] 2022-08-31 08:29
Thanks! The errors are posted above, including the attached [all_errors_from_runtests.py.txt](https://github.com/transientskp/tkp/files/9372104/all_errors_from_runtests.py.txt) file.

I had not used the virtual environment yet, so I will use vagrant now.

**Comment by AntoniaR** [comment] 2022-08-31 08:34
I've not used Vagrant so I don't know if that'll work. I always use virtenv.

Looking at the errors...

1. `ERROR:tkp.sourcefinder.extract:Moments & Gaussian fitting failed at (791L, 630L)` This is normal behaviour so nothing to be concerned about.
2. `ERROR:tkp.db.database:Query failed: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "runningcatalog_xtrsrc_key"` This is a big error and likely the cause of the other errors you see. The database you are using has been corrupted at some point. I recommend that you create a new database before running again.

**Comment by HannoSpreeuw** [comment] 2022-08-31 08:43
Okay, sorry,  I thought you meant a virtual machine. 
Yes, I always use virtual environments, I set one up using conda, so I start by issuing `conda activate python2`.

**Comment by HannoSpreeuw** [comment] 2022-08-31 14:40
@AntoniaR I recreated the database, but `ERROR:tkp.db.database:Query failed: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "config_dataset_section_key_key"` and `ERROR:tkp.db.database:Query failed: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "runningcatalog_xtrsrc_key"` persist. 

[all_output_from_runtests.py_third_attempt.txt](https://github.com/transientskp/tkp/files/9462398/all_output_from_runtests.py_third_attempt.txt) is the output from
`python runtests.py -v > all_output_from_runtests.py_third_attempt.txt 2>&1` ran from the tkp `tests` directory in my `python2` conda virtualenv.

Steps to reproduce:
```
rm -rf tkp_data_cluster
initdb -D tkp_data_cluster
pg_ctl -D tkp_data_cluster -l logfile start
createdb tkp_test_db
export TKP_DBNAME=tkp_test_db
trap-manage.py initdb
```
The latter command gives 
```
/home/hanno/anaconda3/envs/python2/lib/python2.7/site-packages/colorlog/__init__.py:52: UserWarning: Colorlog 6.0.0 will require Python 3.5 or above. Pin 'colorlog<5' to your dependencies if you require compatibility with older versions of Python. See https://github.com/borntyping/python-colorlog#status for more information.
  "Colorlog 6.0.0 will require Python 3.5 or above. Pin 'colorlog<5' to your "

This script will populate a database with these settings:

	engine:     postgresql
	database:   tkp_test_db
	user:       hanno
	password:   hanno
	host:       localhost
	port:       5432

Do you want to continue? [y/N]: y
processing functions/degrad.sql
processing functions/alpha.sql
processing functions/cartesian.sql
processing functions/median.sql
```
and finally
`python runtests.py -v > all_output_from_runtests.py_third_attempt.txt 2>&1`

Do the `duplicate` errors appear?

**Comment by AntoniaR** [comment] 2022-09-01 08:35
I reinstalled, set up a new database and reran the tests - not done this in a while. I have identified the errors that you found.

Basically the tests around source association are failing and I suspect that they have for quite a long time now. I already knew we had issues there as sometimes TraP fails due to source association problems. The vast majority of the time, TraP runs successfully and we circumvent source association issues in later filtering.

As the source association part is going to be re-written and simplified as it has other outstanding problems, I don't think it's wise to input time into fixing this error. I would recommend ignoring it for now for your work in converting to python 3.

**Comment by HannoSpreeuw** [comment] 2022-09-01 14:48
Thanks for verifying that and your advice.

I will proceed with the Python 2 to 3 conversion.

**Comment by HannoSpreeuw** [comment] 2022-09-07 09:38
Couple of warnings from `trap-manage.py initdb` after conversion of tkp to Python3:
```
../tkp/tkp/db/quality.py:10: SAWarning: relationship 'Extractedsource.runningcatalogs' will copy column extractedsource.id to column assocxtrsource.xtrsrc, which conflicts with relationship(s): 'Assocxtrsource.xtrsrc' (copies extractedsource.id to assocxtrsource.xtrsrc). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="xtrsrc"' to the 'Extractedsource.runningcatalogs' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  'rms': Rejectreason(id=0, description='RMS invalid'),
../tkp/tkp/db/quality.py:10: SAWarning: relationship 'Extractedsource.runningcatalogs' will copy column runningcatalog.id to column assocxtrsource.runcat, which conflicts with relationship(s): 'Assocxtrsource.runcat' (copies runningcatalog.id to assocxtrsource.runcat). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="runcat"' to the 'Extractedsource.runningcatalogs' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  'rms': Rejectreason(id=0, description='RMS invalid'),
../tkp/tkp/db/quality.py:10: SAWarning: relationship 'Runningcatalog.extractedsources' will copy column runningcatalog.id to column assocxtrsource.runcat, which conflicts with relationship(s): 'Assocxtrsource.runcat' (copies runningcatalog.id to assocxtrsource.runcat). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="runcat"' to the 'Runningcatalog.extractedsources' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  'rms': Rejectreason(id=0, description='RMS invalid'),
../tkp/tkp/db/quality.py:10: SAWarning: relationship 'Runningcatalog.extractedsources' will copy column extractedsource.id to column assocxtrsource.xtrsrc, which conflicts with relationship(s): 'Assocxtrsource.xtrsrc' (copies extractedsource.id to assocxtrsource.xtrsrc). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="xtrsrc"' to the 'Runningcatalog.extractedsources' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  'rms': Rejectreason(id=0, description='RMS invalid'),

```

**Comment by AntoniaR** [comment] 2022-09-08 07:49
Looks like you're making excellent progress in the conversion - great news! 
These errors are interesting... Not sure if these are important or not yet. When you have completed the conversion, I will try it out on some of my standard datasets to check the results.

**Comment by HannoSpreeuw** [comment] 2022-09-09 10:17
I am presently running into 
```
Can't instantiate abstract class ParamSet with abstract methods __delitem__, __iter__, __len__
File "../tkp/tkp/sourcefinder/extract.py", line 655, in source_profile_and_errors
```
from 
```
param = ParamSet()
```
This has already been fixed by @gijzelaerr [over five years ago in the pyse repo](https://github.com/transientskp/pyse/commit/64b537a389300106136aea1c7729c1410cb392bd).
No point in redoing that great work.

So this is the time to copy the relevant files from the master branch of the pyse repo back into the converted-to-python3 branch of the tkp repo. Or perhaps a new branch from that branch.

This copying back comes at a price. I have been using [futurize](https://python-future.org/automatic_conversion.html) in two stages. Got to 2b in that scheme. pyse is only Python3 compatible, not Python 2, afaik. So copying it back would break that. But perhaps I can fix that in 2d.

**Comment by HannoSpreeuw** [comment] 2022-09-19 15:52
Running into 
```
Exception has occurred: AttributeError       (note: full exception trace is shown but execution is paused at: test_for_invalid_exceptions)
'Database' object has no attribute 'exceptions'
  File "/../../../../tkp/tests/test_database/test_connector.py", line 57, in test_for_invalid_exceptions (Current frame)
 ```
from this code snippet:
```
          for exception in bad_exceptions:
            with self.assertRaises(AttributeError):
                getattr(self.database.exceptions, exception)
```                
So apparently, a database object does not have an attribute `exceptions`.

Checking if this also occurs with the original code, i.e. the current master branch, using an iPython2 shell:
```
In [1]: from tkp import db

In [2]: datab = db.database.Database()

In [3]: datab.exceptions
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-45ea4e4dbd84> in <module>()
----> 1 datab.exceptions

AttributeError: 'Database' object has no attribute `exceptions`.
```

So apparently the `exceptions` attribute did not exist in the original code, using Python 2.

But then the unit test does not make sense. Weird.

**Closed** 2023-03-03 15:41 UTC
Labels: enhancement, priority low
