### ISSUE TITLE
TraP can't handle NaN values in data

### ISSUE THREAD

**Issue by ycendes** [transientskp/tkp#430] opened 2015-06-16 09:49 UTC
Was running TraP on the AA 24 hour run (~37k images) and it failed ~1.7k images into the source extraction stage.  Specifically, the data in question is struis:/scratch/fhuizing/aartfaac/results/24h, and TraP was being run from struis.  My working directory for this is struis:/scratch/ycendes/aartfaac/traptest.

Error message (with last few images that successfully ran) is as follows:

```
INFO:tkp.distribute.multiproc.tasks:running extracted sources task
INFO:tkp.steps.source_extraction:Extracting image: /scratch/fhuizing/aartfaac/results/24h/F5.73257e+07_S1-63_T20-11-2013_14-06-20.image
INFO:tkp.steps.source_extraction:Detected 2 sources in image /scratch/fhuizing/aartfaac/results/24h/F5.73257e+07_S1-63_T20-11-2013_14-06-20.image
INFO:tkp.main:storing extracted sources to database
INFO:tkp.db.general:Inserted 2 sources in extractedsource for image 1749
INFO:tkp.main:performing database operations
INFO:tkp.main:performing DB operations for image 1749
INFO:tkp.main:performing source association
INFO:tkp.steps.forced_fitting:Found 0 null detections
INFO:tkp.main:processing 1 images in timestep 2013-11-20 15:06:21.107520 (1750/37432)
INFO:tkp.main:performing source extraction
INFO:tkp.distribute.multiproc.tasks:running extracted sources task
INFO:tkp.steps.source_extraction:Extracting image: /scratch/fhuizing/aartfaac/results/24h/F5.73257e+07_S1-63_T20-11-2013_14-06-21.image
INFO:tkp.steps.source_extraction:Detected 2 sources in image /scratch/fhuizing/aartfaac/results/24h/F5.73257e+07_S1-63_T20-11-2013_14-06-21.image
INFO:tkp.main:storing extracted sources to database
INFO:tkp.db.general:Inserted 2 sources in extractedsource for image 1750
INFO:tkp.main:performing database operations
INFO:tkp.main:performing DB operations for image 1750
INFO:tkp.main:performing source association
INFO:tkp.steps.forced_fitting:Found 0 null detections
INFO:tkp.main:processing 1 images in timestep 2013-11-20 15:06:22.109760 (1751/37432)
INFO:tkp.main:performing source extraction
INFO:tkp.distribute.multiproc.tasks:running extracted sources task
INFO:tkp.steps.source_extraction:Extracting image: /scratch/fhuizing/aartfaac/results/24h/F5.73257e+07_S1-63_T20-11-2013_14-06-22.image
Traceback (most recent call last):
  File "/soft/trap/aartfaac/bin/trap-manage.py", line 10, in <module>
    tkp.management.main()
  File "/soft/trap/aartfaac/lib/python2.7/site-packages/tkp/management.py", line 335, in main
    args.func(args)
  File "/soft/trap/aartfaac/lib/python2.7/site-packages/tkp/management.py", line 229, in run_job
    run(args.name, monitor_coords)
  File "/soft/trap/aartfaac/lib/python2.7/site-packages/tkp/main.py", line 144, in run
    extraction_results = runner.map("extract_sources", urls, arguments)
  File "/soft/trap/aartfaac/lib/python2.7/site-packages/tkp/distribute/__init__.py", line 42, in map
    return self.module.map(func, iterable, args)
  File "/soft/trap/aartfaac/lib/python2.7/site-packages/tkp/distribute/multiproc/__init__.py", line 23, in map
    return pool.map(func, zipped)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
AssertionError
```

**Comment by ycendes** [comment] 2015-06-16 12:03
Ok, so it appears to be crashing on the same image, and the following is the error you get when it runs in serial mode:

```
INFO:tkp.main:processing 1 images in timestep 2013-11-20 15:06:21.107520 (2/35684)
INFO:tkp.main:performing source extraction
INFO:tkp.distribute.serial.tasks:running extracted sources task
INFO:tkp.steps.source_extraction:Extracting image: /scratch/fhuizing/aartfaac/results/24h/F5.73257e+07_S1-63_T20-11-2013_14-06-21.image
INFO:tkp.steps.source_extraction:Detected 2 sources in image /scratch/fhuizing/aartfaac/results/24h/F5.73257e+07_S1-63_T20-11-2013_14-06-21.image
INFO:tkp.main:storing extracted sources to database
INFO:tkp.db.general:Inserted 2 sources in extractedsource for image 110550
INFO:tkp.main:performing database operations
INFO:tkp.main:performing DB operations for image 110550
INFO:tkp.main:performing source association
INFO:tkp.steps.forced_fitting:Found 0 null detections
INFO:tkp.main:processing 1 images in timestep 2013-11-20 15:06:22.109760 (3/35684)
INFO:tkp.main:performing source extraction
INFO:tkp.distribute.serial.tasks:running extracted sources task
INFO:tkp.steps.source_extraction:Extracting image: /scratch/fhuizing/aartfaac/results/24h/F5.73257e+07_S1-63_T20-11-2013_14-06-22.image
Traceback (most recent call last):
  File "/soft/trap/aartfaac/bin/trap-manage.py", line 10, in <module>
    tkp.management.main()
  File "/soft/trap/aartfaac/lib/python2.7/site-packages/tkp/management.py", line 335, in main
    args.func(args)
  File "/soft/trap/aartfaac/lib/python2.7/site-packages/tkp/management.py", line 229, in run_job
    run(args.name, monitor_coords)
  File "/soft/trap/aartfaac/lib/python2.7/site-packages/tkp/main.py", line 144, in run
    extraction_results = runner.map("extract_sources", urls, arguments)
  File "/soft/trap/aartfaac/lib/python2.7/site-packages/tkp/distribute/__init__.py", line 42, in map
    return self.module.map(func, iterable, args)
  File "/soft/trap/aartfaac/lib/python2.7/site-packages/tkp/distribute/serial/__init__.py", line 3, in map
    x = [func(i, *arguments) for i in iterable]
  File "/soft/trap/aartfaac/lib/python2.7/site-packages/tkp/distribute/serial/tasks.py", line 22, in extract_sources
    return tkp.steps.source_extraction.extract_sources(url, extraction_params)
  File "/soft/trap/aartfaac/lib/python2.7/site-packages/tkp/steps/source_extraction.py", line 50, in extract_sources
    force_beam=extraction_params['force_beam']
  File "/soft/trap/aartfaac/lib/python2.7/site-packages/tkp/sourcefinder/image.py", line 401, in extract
    det * self.rmsmap, anl * self.rmsmap, deblend_nthresh, force_beam,
  File "/soft/trap/aartfaac/lib/python2.7/site-packages/tkp/utility/memoize.py", line 29, in __call__
    self.memo[instance] = self.funct(instance)
  File "/soft/trap/aartfaac/lib/python2.7/site-packages/tkp/sourcefinder/image.py", line 114, in _get_rm
    return self._interpolate(self.grids['rms'], roundup=True)
  File "/soft/trap/aartfaac/lib/python2.7/site-packages/tkp/utility/memoize.py", line 29, in __call__
    self.memo[instance] = self.funct(instance)
  File "/soft/trap/aartfaac/lib/python2.7/site-packages/tkp/sourcefinder/image.py", line 92, in _grids
    return self.__grids()
  File "/soft/trap/aartfaac/lib/python2.7/site-packages/tkp/sourcefinder/image.py", line 218, in __grids
    assert(len(useful_chunk) == 1)
AssertionError
```

**Comment by timstaley** [comment] 2015-06-16 12:18
Thanks @ycendes , that second error message is much more helpful. How big are the image files? Could you make the problematic one available somehow?

**Comment by ycendes** [comment] 2015-06-16 12:24
The image file is here: https://www.dropbox.com/s/t42s6e7bbesi9il/F5.73257e%2B07_S1-63_T20-11-2013_14-06-22.image.zip?dl=0

**Comment by ycendes** [comment] 2015-06-16 15:09
Another update!  The image in question that makes it crash looks like a "bad" image, with no sources, so that's why the sourcefinder must be crashing.  See here: https://www.dropbox.com/s/jnrk5iq6s11ijs3/Screen%20Shot%202015-06-16%20at%205.06.43%20PM.png?dl=0

So basically, we need a quality control step or similar before sourcefinding to toss the bad images?  Or should that already be happening?

**Comment by gijzelaerr** [comment] 2015-06-16 15:39
interesting, i think we have found us a new test case for the source finder.

anyway, the sourcefinder should never raise an exception, except for when the image format or corrupt or something. It should still accept an empty image.

**Comment by ycendes** [comment] 2015-06-16 16:22
Woohoo!

Ok, so I have been running it to find the "bad" images and see if we can run the TraP anyway, but it appears there are too many.  Currently,

```
BAD_IMAGES = set(['F5.73257e+07_S1-63_T20-11-2013_14-06-22.image','F5.73257e+07_S1-63_T20-11-2013_14-06-32.image','F5.73257e+07_S1-63_T20-11-2013_14-06-45.image'])
```
Given the 35k+ images, and I'm going on holiday tomorrow, perhaps it's easier to just tell TraP to keep running through them and ignore them over me finding the bad ones by hand?  Cheers.

**Comment by ajstewart** [comment] 2015-06-16 20:03
Hey, looking at these images you mention, I believe the issue is that they are just full of nans. In my home directory on struis there is a text file:

~as/bad_images.txt

which lists all the images which contain a nan value (generated by ~as/check-bad-images.py). The first three match up with the ones you found, and in total there are only 41/37,000 (not bad!).

Personally I would load up this bad_images list in images_to_process.py and have it remove these images from the overall list.

Hope this helps!

**Comment by AntoniaR** [comment] 2015-06-16 23:56
Yes, bad images that are full of nans etc are going cause issues. I agree with Adam that in the initial scenario we should just remove the images from the images_to_process.py file.

The RMS quality control script that I have will very easily identify and get rid of those images automatically when it creates the images_to_process.py file. As I said on the AARTFAAC telecon, I will get a version of this script working for AARTFAAC images and was aiming to get this in place for when you get back from holiday. So in the mean time, flag them out by hand.

In the longer term, we can convert my script into an automated quality control script in TraP. This shouldn't be too difficult but we want to have it tested first.

**Comment by timstaley** [comment] 2015-06-17 20:23
So, if NaNs are a sign of bad data, then it sounds like we should just add a 'discard images with NaNs in' step as part of the quality control for all telescopes - this should be trivial, and is something we could do right away. Any objections - do we ever get NaNs in good images, that anyone knows of?

**Comment by gijzelaerr** [comment] 2015-06-17 20:33
i still think the sourcefinder should be able to eat this, and not just
bail out.

2015-06-17 22:23 GMT+02:00 Tim Staley <notifications@github.com>:

> So, if NaNs are a sign of bad data, then it sounds like we should just add
> a 'discard images with NaNs in' step as part of the quality control for all
> telescopes - this should be trivial, and is something we could do right
> away. Any objections - do we ever get NaNs in good images, that anyone
> knows of?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transientskp/tkp/issues/430#issuecomment-112938951>.
>



-- 
Gijs Molenaar
http://pythonic.nl

**Comment by jbroderick1** [comment] 2015-06-17 20:57
I agree - PyBDSM has some functionality to take care of this, for example.

In terms of quality control, I have an example of a good image with just a few NaNs in it (at least you get NaNs when you load it in Matlab). It's an old SS433 map from the VLA. It might be because it looks like a cutout of the central region of a larger map, and something went wrong at one of the boundaries. 

This is probably a very rare case, though.....

**Comment by ajstewart** [comment] 2015-06-17 22:00
I would also agree that it probably would be good if it was solved at the source extractor, then it's solved for good. As Gijs said, I think it shouldn't just fall over because of a Nan value.

The source extractor can cope with finding nothing? Perhaps just a simple action similar to numpy nan to num would suffice?

**Comment by AntoniaR** [comment] 2015-06-18 03:42
I don't think we should discard images with NaNs in - if there are NaNs outside the source extraction region we don't care and we will want the image to still be processed. So I think we should limit this to only NaNs within the source extraction region.

**Comment by jdswinbank** [comment] 2015-06-18 07:50
The existence of NaNs in the image is just a symptom of some underlying issue. Unless you understand what that issue is, you can't make an informed decision on how to proceed.

To expand a bit: my first reaction is to be pretty sceptical of any image which contains NaNs -- if some pixels are obviously invalid, what makes you think the others contain useful data rather than just being broken in some more subtle way? Of course, there may be perfectly good reasons for NaNs to sneak in along with valid data, but you need to be confident that you not only have some idea of what those reasons might be but that you can explicitly account for each NaN in terms of them before you proceed.

Beyond that, I imagine we can all agree that throwing an unhandled exception is not the correct response. However, what it means for the sourcefinder to "eat" or "take care of" NaNs is not obvious (and probably depends on the answer to my previous point). Do you mean simply skipping the image and logging a warning? Masking out the NaNs? Interpolating over them? Something else?

**Comment by gijzelaerr** [comment] 2015-06-18 08:44
Ah thanks, didn't realise NaN where actually invalid but that makes sense. @Error323 did you know your AARTFAAC images container NaN values?

I propose we let the sourcefinder handle this, but let it log warning/error messages. That way a pipeline won't crash

**Comment by gijzelaerr** [comment] 2015-06-18 08:47
And maybe also add a quality control check where a scientist can optionally drop an image with NaN values?

Or should we just assume that is too obscure (never happened until now) that it would just at more complex unnecessary logic?

**Comment by timstaley** [comment] 2015-06-18 15:41
I vote for a 'dropnans' setting in the quality config - so you can choose to drop all NaNs by default / if appropriate. That should also solve the immediate issue of allowing Yvette to process here data. Then in the longer run we can fix up the sourcefinder to ignore islands that have NaNs in (and log warnings).

**Comment by AntoniaR** [comment] 2015-06-18 21:39
I think if there are nans in the source extraction region there is something bad going on and the image should always be rejected. Outside the source extraction region it could just be something in the imaging settings - for instance if you image out to large radii you can start to see very huge numbers (so I don't think it's a stretch to imagine cases where it could be nan out there) where the primary beam is noisy - but the images are great quality where you want to process.
So I am pro rejecting images that have nans in the source extraction region, and don't think it even needs to be an option - nans are bad. But I would be cautious of just rejecting the image if there are nans outside the source extraction region.
However, I still very strongly suspect that a separate quality control step is not needed. I am reasonably confident that these would be rejected by a simple rms quality control step. I think I have had images with nans before that are rejected by this. I am developing a stand-alone rms quality control script for non lofar images that writes the images_to_process.py file and will have a version for aartfaac soon. Once tested for aartfaac (already tested for MWA, ATCA and BETA) we can think about the best way to implement in TraP. 
As I said earlier, I have promised Yvete a version of this script when she gets back from holiday, and this should be the fastest way to get it working without needing any changes to TraP. We can then also see if a further quality control step is needed or if our basic rms check is sufficient.

**Comment by Error323** [comment] 2015-06-19 12:04
Allright, so this NaN field is due to the unstable nature of the calibration algorithm. There probably was something bright that messed up our assumptions wrt to the source model. Clearly these images should be discarded, I don't think it makes much sense to look for NaNs on my side and replace them with zeros, instead I suggest to just discard an image consisting of NaNs allround.

@hsuyeep Can you give your thoughts on this as well?

**Comment by hsuyeep** [comment] 2015-06-19 12:48
On 19-Jun-2015, at 2:04 PM, F. Huizinga wrote:

> Allright, so this NaN field is due to the unstable nature of the calibration algorithm. There probably was something bright that messed up our assumptions wrt to the source model. Clearly these images should be discarded, I don't think it makes much sense to look for NaNs on my side and replace them with zeros, instead I suggest to just discard an image consisting of NaNs allround.
> 
I just had a look at the timestamp in question... the ACM appears quite normal, and similar to the adjoining timeslices. F, are the timestamps on your image filename in UTC or CET?  I've been looking at the MJDsec (which is CET) corresponding to 14:06:22...

Also, a bad calibration does not result in all NaNs, it just moves the Sun to the position of CasA, and so shifts all the other sources as well. First guess is that some NaN visibilities might be sneaking through and contributing a NaN to every pixel via the FFT. F, do you have a filter for NaN visibilities?

-- P

**Comment by Error323** [comment] 2015-06-19 12:58
Timestamp is UTC! So please re-verify. I do perform NaN filtering at some place in the code. But I'll fix it before imaging then.

**Comment by gijzelaerr** [comment] 2015-07-13 11:03
For the sake of progress I have implemented a NaN quality check and committed it to the AARTFAAC branch:

https://github.com/transientskp/tkp/commit/887eeac7248d5ec5689b99ec05038e654927bafe

Yvette is doing a test run as we speak.

**Comment by gijzelaerr** [comment] 2015-07-23 15:51
This has been resolved in the AARTFAAC branch. We can close this when it is merged.

**Comment by gijzelaerr** [comment] 2015-07-28 08:44
Actually there are 2 issues discussed here, 1 is solved and the other is a duplicate of an other error previously reported: https://github.com/transientskp/tkp/issues/415. 

I'm closing this issue.

**Closed by gijzelaerr** 2015-07-28 08:44 UTC
Labels: aartfaac, bug, priority high
