### ISSUE TITLE
Coordinate Conversion for RA Values is Incorrect

### ISSUE THREAD

**Issue by ycendes** [transientskp/tkp#449] opened 2015-07-22 17:23 UTC
I was mulling over just where to file this issue, but figured it's better to file one and have you guys argue over where it falls as I don't think this is an AARTFAAC-unique issue.

While trying to work out the coordinates in more detail in the AARTFAAC images, I ran into a strange bug in the sources found which you can see both on Banana (ie TraP output) and when running pyse.py (and on all the AARTFAAC images).  In short, if you extract sources, they look like this:
```
« 1 » Flux units CSV format
Id	Ra(°)	Dec(°)	Ra Error(″)	Dec Error(″)	Sexagesimal 	Peak Flux (Jy)	Peak Flux err (Jy)	Int. flux (Jy)	Int. flux err (Jy)
138523
-48.690	50.702	697.414	338.217	(20h 45m 14.4s, +50° 42′ 08.1″) ± (46.494s, 338.217″)	0.4758	0.0610	1.0969	0.1934
138524
-54.586	40.324	165.116	143.102	(20h 21m 39.4s, +40° 19′ 27.1″) ± (11.008s, 143.102″)	1.4535	0.0896	1.5017	0.1599
```
(Ugh, the above looks fine to me when I edit, but not when I publish, so here's the pyse.py readout too...)

```
ycendes@struis:~$ pyse.py --detection=2 --analysis=3 --regions --islands --deblend-thresholds=100 --radius=250 --csv --rmsmap --sigmap --grid=50 test.fits 
Processing test.fits (file 1 of 1).
WARNING:tkp.accessors.fitsimage:End time not specified or unreadable
Thresholding with det = 6.000000 sigma, analysis = 3.000000 sigma
** test.fits **

RA: -54.6966+-0.0473894, dec: 40.3772+-0.0386048
Error radius (arcsec): 206.282113933
Semi-major axis (arcsec): 1970.71+-125.513
Semi-minor axis (arcsec): 1858.54+-110.714
Position angle: 146.769+-35.131
Flux: 1.61177+-0.169148
Peak: 1.52442+-0.0938975

RA: -55.0246+-0.173047, dec: 45.6186+-0.119517
Error radius (arcsec): 657.944551491
Semi-major axis (arcsec): 2646.59+-459.999
Semi-minor axis (arcsec): 2024.03+-289.217
Position angle: 118.195+-22.7709
Flux: 0.871069+-0.208022
Peak: 0.541835+-0.0853897
```

That is, *all* the RA degree values are negative- Dec appears to be correct though.  Note, however, if you look at the sexagesimal RA/Dec values, they're perfectly correct (and while I'm not saying anything definitive yet, it appears that the sources will load correctly in Aladin with the correct RA/Dec values).  As such, it appears to me at least that this might just be something really weird just in how the RA values shown are displayed, because it makes little sense to me that the sexagesimal ones would be correct... but I leave the more firm conclusion of what's going on to the experts.

**Comment by gijzelaerr** [comment] 2015-08-12 09:13
this is a duplicate of

https://github.com/transientskp/tkp/issues/450

**Closed by gijzelaerr** 2015-08-12 09:13 UTC
